"""
Competitor model

Represents a competitor brand added to an analysis.
"""
from datetime import datetime
from sqlalchemy import Column, String, DateTime, ForeignKey, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from core.database import Base


class Competitor(Base):
    """
    Competitor brand entity

    Represents a competitor added to an analysis. Can be either:
    - AI-suggested (is_suggested=True): Generated by Claude
    - User-added (is_suggested=False): Manually added by user

    Constraints:
    - Maximum 5 competitors per analysis (enforced in service layer)
    - Unique competitor names within an analysis (enforced in service layer)
    """
    __tablename__ = "competitors"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    analysis_id = Column(
        UUID(as_uuid=True),
        ForeignKey("analyses.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    name = Column(String(255), nullable=False, index=True)
    is_suggested = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    analysis = relationship("Analysis", back_populates="competitors")

    def __repr__(self) -> str:
        suggested_flag = "AI" if self.is_suggested else "User"
        return f"<Competitor(id={self.id}, name={self.name}, type={suggested_flag})>"
